# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_DB.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1009, 831)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../santdex/trilobit.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(5, 45, 100);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(9, 20, 971, 581))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 971, 581))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setBaseSize(QtCore.QSize(0, 50))
        self.tableWidget.setStyleSheet("background-color: rgb(240, 250, 255);\n"
"\n"
"color: rgb(0, 0, 79);")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setRowCount(15)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(131)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 680, 971, 101))
        self.frame_3.setStyleSheet("background-color: rgb(15, 75, 125);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lbl_4 = QtWidgets.QLabel(self.frame_3)
        self.lbl_4.setGeometry(QtCore.QRect(240, 10, 61, 18))
        self.lbl_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_4.setObjectName("lbl_4")
        self.lbl_5 = QtWidgets.QLabel(self.frame_3)
        self.lbl_5.setGeometry(QtCore.QRect(10, 60, 41, 18))
        self.lbl_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_5.setObjectName("lbl_5")
        self.txt_add_subtype = QtWidgets.QTextEdit(self.frame_3)
        self.txt_add_subtype.setGeometry(QtCore.QRect(300, 10, 141, 31))
        self.txt_add_subtype.setStyleSheet("background-color: rgb(5, 45, 100);\n"
"color: rgb(255, 255, 255);")
        self.txt_add_subtype.setObjectName("txt_add_subtype")
        self.txt_add_name = QtWidgets.QTextEdit(self.frame_3)
        self.txt_add_name.setGeometry(QtCore.QRect(50, 50, 141, 31))
        self.txt_add_name.setStyleSheet("background-color: rgb(5, 45, 100);\n"
"color: rgb(255, 255, 255);")
        self.txt_add_name.setObjectName("txt_add_name")
        self.txt_add_location = QtWidgets.QTextEdit(self.frame_3)
        self.txt_add_location.setGeometry(QtCore.QRect(260, 50, 81, 31))
        self.txt_add_location.setStyleSheet("background-color: rgb(5, 45, 100);\n"
"color: rgb(255, 255, 255);")
        self.txt_add_location.setObjectName("txt_add_location")
        self.txt_add_qty = QtWidgets.QTextEdit(self.frame_3)
        self.txt_add_qty.setGeometry(QtCore.QRect(510, 10, 81, 31))
        self.txt_add_qty.setStyleSheet("background-color: rgb(5, 45, 100);\n"
"color: rgb(255, 255, 255);")
        self.txt_add_qty.setObjectName("txt_add_qty")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(480, 10, 31, 18))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.lbl_7 = QtWidgets.QLabel(self.frame_3)
        self.lbl_7.setGeometry(QtCore.QRect(200, 60, 51, 18))
        self.lbl_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_7.setObjectName("lbl_7")
        self.txt_add_price = QtWidgets.QTextEdit(self.frame_3)
        self.txt_add_price.setGeometry(QtCore.QRect(670, 10, 91, 31))
        self.txt_add_price.setStyleSheet("background-color: rgb(5, 45, 100);\n"
"color: rgb(255, 255, 255);")
        self.txt_add_price.setObjectName("txt_add_price")
        self.lbl_8 = QtWidgets.QLabel(self.frame_3)
        self.lbl_8.setGeometry(QtCore.QRect(600, 10, 61, 18))
        self.lbl_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_8.setObjectName("lbl_8")
        self.lbl_9 = QtWidgets.QLabel(self.frame_3)
        self.lbl_9.setGeometry(QtCore.QRect(350, 60, 61, 18))
        self.lbl_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_9.setObjectName("lbl_9")
        self.txt_add_data = QtWidgets.QTextEdit(self.frame_3)
        self.txt_add_data.setGeometry(QtCore.QRect(420, 50, 171, 31))
        self.txt_add_data.setStyleSheet("background-color: rgb(5, 45, 100);\n"
"color: rgb(255, 255, 255);")
        self.txt_add_data.setObjectName("txt_add_data")
        self.txt_add_package = QtWidgets.QTextEdit(self.frame_3)
        self.txt_add_package.setGeometry(QtCore.QRect(850, 10, 111, 31))
        self.txt_add_package.setStyleSheet("background-color: rgb(5, 45, 100);\n"
"color: rgb(255, 255, 255);")
        self.txt_add_package.setObjectName("txt_add_package")
        self.lbl_10 = QtWidgets.QLabel(self.frame_3)
        self.lbl_10.setGeometry(QtCore.QRect(790, 10, 51, 18))
        self.lbl_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_10.setObjectName("lbl_10")
        self.lbl_6 = QtWidgets.QLabel(self.frame_3)
        self.lbl_6.setGeometry(QtCore.QRect(10, 10, 41, 18))
        self.lbl_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_6.setObjectName("lbl_6")
        self.comboBox_Add_Cat = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_Add_Cat.setGeometry(QtCore.QRect(50, 10, 161, 31))
        self.comboBox_Add_Cat.setStyleSheet("background-color: rgb(5, 45, 100);\n"
"color: rgb(255, 255, 255);")
        self.comboBox_Add_Cat.setObjectName("comboBox_Add_Cat")
        self.comboBox_Add_Cat.addItem("")
        self.comboBox_Add_Cat.addItem("")
        self.comboBox_Add_Cat.addItem("")
        self.comboBox_Add_Cat.addItem("")
        self.comboBox_Add_Cat.addItem("")
        self.comboBox_Add_Cat.addItem("")
        self.comboBox_Add_Cat.addItem("")
        self.comboBox_Add_Cat.addItem("")
        self.comboBox_Add_Cat.addItem("")
        self.comboBox_Add_Cat.addItem("")
        self.comboBox_Add_Cat.addItem("")
        self.comboBox_Add_Cat.addItem("")
        self.comboBox_Add_Cat.addItem("")
        self.comboBox_Add_Cat.addItem("")
        self.comboBox_Add_Cat.addItem("")
        self.comboBox_Add_Cat.addItem("")
        self.txt_add_info = QtWidgets.QTextEdit(self.frame_3)
        self.txt_add_info.setGeometry(QtCore.QRect(630, 50, 331, 31))
        self.txt_add_info.setStyleSheet("background-color: rgb(5, 45, 100);\n"
"color: rgb(255, 255, 255);")
        self.txt_add_info.setObjectName("txt_add_info")
        self.lbl_11 = QtWidgets.QLabel(self.frame_3)
        self.lbl_11.setGeometry(QtCore.QRect(600, 60, 31, 18))
        self.lbl_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_11.setObjectName("lbl_11")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 0, 101, 18))
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 630, 971, 51))
        self.frame_2.setStyleSheet("background-color: rgb(15, 75, 125);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lbl_2 = QtWidgets.QLabel(self.frame_2)
        self.lbl_2.setGeometry(QtCore.QRect(10, 20, 61, 18))
        self.lbl_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_2.setObjectName("lbl_2")
        self.comboBox_cat = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_cat.setGeometry(QtCore.QRect(80, 10, 161, 31))
        self.comboBox_cat.setStyleSheet("background-color: rgb(5, 45, 100);\n"
"color: rgb(255, 255, 255);")
        self.comboBox_cat.setObjectName("comboBox_cat")
        self.comboBox_cat.addItem("")
        self.comboBox_cat.addItem("")
        self.comboBox_cat.addItem("")
        self.comboBox_cat.addItem("")
        self.comboBox_cat.addItem("")
        self.comboBox_cat.addItem("")
        self.comboBox_cat.addItem("")
        self.comboBox_cat.addItem("")
        self.comboBox_cat.addItem("")
        self.comboBox_cat.addItem("")
        self.comboBox_cat.addItem("")
        self.comboBox_cat.addItem("")
        self.comboBox_cat.addItem("")
        self.comboBox_cat.addItem("")
        self.comboBox_cat.addItem("")
        self.comboBox_cat.addItem("")
        self.comboBox_cat.addItem("")
        self.btn_search = QtWidgets.QPushButton(self.frame_2)
        self.btn_search.setGeometry(QtCore.QRect(430, 10, 81, 31))
        self.btn_search.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_search.setObjectName("btn_search")
        self.btn_rmItem = QtWidgets.QPushButton(self.frame_2)
        self.btn_rmItem.setGeometry(QtCore.QRect(520, 10, 101, 31))
        self.btn_rmItem.setStyleSheet("background-color: rgb(5, 45, 100);\n"
"color: rgb(255, 0, 0);\n"
"border-color: rgb(255, 0, 0);")
        self.btn_rmItem.setObjectName("btn_rmItem")
        self.line_search = QtWidgets.QLineEdit(self.frame_2)
        self.line_search.setGeometry(QtCore.QRect(250, 10, 171, 31))
        self.line_search.setStyleSheet("background-color: rgb(5, 45, 100);\n"
"color: rgb(255, 255, 255);")
        self.line_search.setObjectName("line_search")
        self.btn_save = QtWidgets.QPushButton(self.frame_2)
        self.btn_save.setGeometry(QtCore.QRect(860, 10, 101, 31))
        self.btn_save.setStyleSheet("background-color: rgb(5, 45, 100);\n"
"border-color: rgb(255, 255, 0);\n"
"color: rgb(255, 255, 0);")
        self.btn_save.setObjectName("btn_save")
        self.btn_editItem = QtWidgets.QPushButton(self.frame_2)
        self.btn_editItem.setGeometry(QtCore.QRect(630, 10, 101, 31))
        self.btn_editItem.setStyleSheet("background-color: rgb(5, 45, 100);\n"
"color: rgb(0, 255, 255);\n"
"border-color: rgb(0, 255, 255);")
        self.btn_editItem.setObjectName("btn_editItem")
        self.btn_addItem = QtWidgets.QPushButton(self.frame_2)
        self.btn_addItem.setGeometry(QtCore.QRect(740, 10, 101, 31))
        self.btn_addItem.setStyleSheet("background-color: rgb(5, 45, 100);\n"
"color: rgb(0, 255, 0);\n"
"border-color: rgb(85, 255, 0);")
        self.btn_addItem.setObjectName("btn_addItem")
        self.lineEdit_info = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_info.setGeometry(QtCore.QRect(80, 600, 901, 32))
        self.lineEdit_info.setObjectName("lineEdit_info")
        self.lbl_3 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_3.setGeometry(QtCore.QRect(20, 610, 61, 20))
        self.lbl_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_3.setObjectName("lbl_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1009, 30))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionExit)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DAMASYS v0.1"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "type"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "sub-type"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "qty"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "location"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "price (€)"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "package"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.lbl_4.setText(_translate("MainWindow", "Sub-type"))
        self.lbl_5.setText(_translate("MainWindow", "name"))
        self.label.setText(_translate("MainWindow", "Qty"))
        self.lbl_7.setText(_translate("MainWindow", "Location"))
        self.lbl_8.setText(_translate("MainWindow", "Unit price"))
        self.lbl_9.setText(_translate("MainWindow", "Datasheet"))
        self.lbl_10.setText(_translate("MainWindow", "Package"))
        self.lbl_6.setText(_translate("MainWindow", "Type"))
        self.comboBox_Add_Cat.setItemText(0, _translate("MainWindow", "Transistor"))
        self.comboBox_Add_Cat.setItemText(1, _translate("MainWindow", "Mosfet"))
        self.comboBox_Add_Cat.setItemText(2, _translate("MainWindow", "JFet"))
        self.comboBox_Add_Cat.setItemText(3, _translate("MainWindow", "Opamp"))
        self.comboBox_Add_Cat.setItemText(4, _translate("MainWindow", "Resistor"))
        self.comboBox_Add_Cat.setItemText(5, _translate("MainWindow", "Capacitor"))
        self.comboBox_Add_Cat.setItemText(6, _translate("MainWindow", "Diode"))
        self.comboBox_Add_Cat.setItemText(7, _translate("MainWindow", "Inductor"))
        self.comboBox_Add_Cat.setItemText(8, _translate("MainWindow", "Voltage Regulator"))
        self.comboBox_Add_Cat.setItemText(9, _translate("MainWindow", "Microcontroller"))
        self.comboBox_Add_Cat.setItemText(10, _translate("MainWindow", "Crystals"))
        self.comboBox_Add_Cat.setItemText(11, _translate("MainWindow", "Logic"))
        self.comboBox_Add_Cat.setItemText(12, _translate("MainWindow", "Development Board"))
        self.comboBox_Add_Cat.setItemText(13, _translate("MainWindow", "Adapter board"))
        self.comboBox_Add_Cat.setItemText(14, _translate("MainWindow", "CMOS"))
        self.comboBox_Add_Cat.setItemText(15, _translate("MainWindow", "Other"))
        self.lbl_11.setText(_translate("MainWindow", "Info"))
        self.label_2.setText(_translate("MainWindow", "DAMASYS v0.1"))
        self.lbl_2.setText(_translate("MainWindow", "Category:"))
        self.comboBox_cat.setItemText(0, _translate("MainWindow", "All"))
        self.comboBox_cat.setItemText(1, _translate("MainWindow", "Transistor"))
        self.comboBox_cat.setItemText(2, _translate("MainWindow", "Mosfet"))
        self.comboBox_cat.setItemText(3, _translate("MainWindow", "JFet"))
        self.comboBox_cat.setItemText(4, _translate("MainWindow", "Opamp"))
        self.comboBox_cat.setItemText(5, _translate("MainWindow", "Resistor"))
        self.comboBox_cat.setItemText(6, _translate("MainWindow", "Capacitor"))
        self.comboBox_cat.setItemText(7, _translate("MainWindow", "Diode"))
        self.comboBox_cat.setItemText(8, _translate("MainWindow", "Inductor"))
        self.comboBox_cat.setItemText(9, _translate("MainWindow", "Voltage Regulator"))
        self.comboBox_cat.setItemText(10, _translate("MainWindow", "Microcontroller"))
        self.comboBox_cat.setItemText(11, _translate("MainWindow", "Crystals"))
        self.comboBox_cat.setItemText(12, _translate("MainWindow", "Logic"))
        self.comboBox_cat.setItemText(13, _translate("MainWindow", "Development Board"))
        self.comboBox_cat.setItemText(14, _translate("MainWindow", "Adapter board"))
        self.comboBox_cat.setItemText(15, _translate("MainWindow", "CMOS"))
        self.comboBox_cat.setItemText(16, _translate("MainWindow", "Other"))
        self.btn_search.setText(_translate("MainWindow", "Search"))
        self.btn_rmItem.setText(_translate("MainWindow", "Remove item"))
        self.btn_save.setText(_translate("MainWindow", "Save DB"))
        self.btn_editItem.setText(_translate("MainWindow", "Edit item"))
        self.btn_addItem.setText(_translate("MainWindow", "Add item"))
        self.lbl_3.setText(_translate("MainWindow", "Misc. Info:"))
        self.menuAbout.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
